### ISSUE TITLE
splits for the datasets

### ISSUE THREAD

**Issue by SiyuanHuangSJTU** [zaixizhang/ANS-GT#3]
Hello! You have done a wonderful work. I have a strong interest in following your work. I am wondering what is the detailed implementation of your experiements for the Table 1. In the paper you have mentioned "We apply 3 independent runs on random data splitting and report the means and standard deviations." Does this mean that you ran the experiment on three different splits, or ran on the same split for three times ? Thanks a lot for your attention to this question.

**Comment by zaixizhang** [comment]
Thanks for your interest in our work! We ran the experiment on three different splits in our work.

**Comment by SiyuanHuangSJTU** [comment]
Hello ! thank you for your reply. Is it convenient for you to provide these splits? Because it seems that the current code does not have a section to generate such three splits.

**Comment by zaixizhang** [comment]
Hi! We randomly sample nodes for data splitting. It is convenient to use  random_split function in main_adaptive.py to obtain the splits. You can use seeds 0, 1, 2.

**Comment by SiyuanHuangSJTU** [comment]
Hello ! I understand, thanks for your reply !
