### ISSUE TITLE
Memory Requirement for Preprocessing Large Datasets

### ISSUE THREAD

**Issue by isaduan001** [zaixizhang/ANS-GT#4]
I tried running preprocess_data.py on the Reddit dataset. I ran the program on one NVIDIA Tesla V100 GPU. However, I get out-of-memory errors when trying to create eigen_adj in the process_data method (I'm assuming due to converting to a dense matrix).

I read in your paper that you were able to train the model on the much larger ogbn-arxiv and ogbn-products using an NVIDIA Tesla V100 GPU. Did you use the same preprocessing code as listed in the GitHub for these datasets? If so, how much memory was needed?

Thanks in advance!

**Comment by zaixizhang** [comment]
Hi, thanks for your interest in our work. How large is the dataset? Could you provide more details of the out-of-memory issue, e.g., screen shots?

**Comment by zaixizhang** [comment]
You can also take a look at the preprocess_data_large.py
